extends: "@redhat-cloud-services/eslint-config-redhat-cloud-services"
globals:
  insights: 'readonly'
  shallow: readonly
  render: 'readonly'
  mount: 'readonly'
rules:
  # We are transforming the imports in babel, so we don't need to enforce this rule
  rulesdir/forbid-pf-relative-imports: 'off'
